#!name=Spotify Premium
#!desc=2025.6.27 部分解锁premium,音质不能设置为超高(建议登录后再打开脚本,重启app等待脚本生效)。功能: 去除播放广告、歌手/专辑列表正常展示、去除随机播放
#!author=daozen
#!homepage=https://github.com/daozen/rules
#!icon=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png
#!date=2025-06-27
#############################################

[Script]
http-request ^https:\/\/(?:\w+-spclient|spclient\.wg)\.spotify\.com(?::443)?\/user-customization-service\/v1\/customize$ script-path=https://raw.githubusercontent.com/daozen/rules/master/js/spotify-qx-header.js, requires-body=false, timeout=10, tag=Spotify Customize Header
http-response ^https:\/\/(?:\w+-spclient|spclient\.wg)\.spotify\.com(?::443)?\/(?:bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$ script-path=https://raw.githubusercontent.com/daozen/rules/master/js/spotify-proto.js, requires-body=true, binary-body-mode=true, timeout=10, tag=Spotify Proto
http-request ^https:\/\/(?:\w+-spclient|spclient\.wg)\.spotify\.com(?::443)?\/(?:artistview\/v1\/artist|album-entity-view\/v2\/album)\/ script-path=https://raw.githubusercontent.com/daozen/rules/master/js/spotify-json.js, requires-body=false, timeout=10, tag=Spotify JSON

[MITM]
hostname = *-spclient.spotify.com, spclient.wg.spotify.com
